# Generated by Django 4.2.7 on 2025-08-03 22:12

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('descricao', models.TextField(help_text='Descreva detalhadamente a tarefa a ser realizada', verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, help_text='Indica se a tarefa está ativa ou foi concluída', verbose_name='Tarefa Ativa')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Registro')),
                ('tempo_trabalhado', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=60))], verbose_name='Tempo Trabalhado')),
                ('descricao_trabalho', models.TextField(help_text='Descreva o que foi realizado durante este período', verbose_name='Descrição do Trabalho')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação do Registro')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_tempo', to='time_tracking.tarefa', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Registro de Tempo',
                'verbose_name_plural': 'Registros de Tempo',
                'ordering': ['-data_registro', '-data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['usuario_responsavel', '-data_criacao'], name='time_tracki_usuario_ce3380_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['ativa', '-data_criacao'], name='time_tracki_ativa_fbe0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='registrotempo',
            index=models.Index(fields=['tarefa', '-data_registro'], name='time_tracki_tarefa__6c0779_idx'),
        ),
        migrations.AddIndex(
            model_name='registrotempo',
            index=models.Index(fields=['data_registro', '-data_criacao'], name='time_tracki_data_re_ccb05d_idx'),
        ),
    ]
