# Generated by Django 4.2.7 on 2025-08-03 22:30

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('description', models.TextField(help_text='Describe the task in detail', verbose_name='Description')),
                ('active', models.BooleanField(default=True, help_text='Indicates if the task is active or completed', verbose_name='Active Task')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsible User')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=django.utils.timezone.now, verbose_name='Record Date')),
                ('worked_time', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=60))], verbose_name='Worked Time')),
                ('work_description', models.TextField(help_text='Describe what was done during this period', verbose_name='Work Description')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Record Creation Date')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to='time_tracking.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Time Record',
                'verbose_name_plural': 'Time Records',
                'ordering': ['-record_date', '-creation_date'],
            },
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='usuario_responsavel',
        ),
        migrations.DeleteModel(
            name='RegistroTempo',
        ),
        migrations.DeleteModel(
            name='Tarefa',
        ),
        migrations.AddIndex(
            model_name='timerecord',
            index=models.Index(fields=['task', '-record_date'], name='time_tracki_task_id_b07f90_idx'),
        ),
        migrations.AddIndex(
            model_name='timerecord',
            index=models.Index(fields=['record_date', '-creation_date'], name='time_tracki_record__3d0dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['responsible_user', '-creation_date'], name='time_tracki_respons_3f5d37_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['active', '-creation_date'], name='time_tracki_active_dd20ea_idx'),
        ),
    ]
